# ======================================================================
# BALL TRACKER
# ======================================================================
# Webapp pipeline equivalent of the ball tracking stage
#
# INPUT:
#   YOLO detection CSV generated by ball_detector.py
#
# PIPELINE:
#   YOLO detections
#        ↓
#   Ball position extraction
#        ↓
#   Interpolation on ORIGINAL sampled-frame timeline
#        ↓
#   Kalman filtering
#        ↓
#   Final ball trajectory
#
# IMPORTANT:
#   The detector samples every 2nd frame.
#   Therefore the tracker MUST preserve those sampled frames.
#
#   Example:
#
#       Original video       : 3,500 frames
#       YOLO sampled frames  : 1,750
#       Interpolated rows    : 1,750
#       Kalman rows          : 1,750
#       Final trajectory     : 1,750
#
# ======================================================================

import os
import numpy as np
import pandas as pd
import cv2


# ======================================================================
# SETTINGS
# ======================================================================

# Maximum number of consecutive sampled frames that interpolation
# is allowed to fill.
MAX_INTERPOLATION_GAP = 15

# Maximum number of sampled frames for which Kalman prediction
# is allowed to continue without a fresh YOLO detection.
MAX_KALMAN_GAP = 15

# Maximum allowed Kalman movement between sampled frames.
# This prevents extreme jumps from corrupting the trajectory.
MAX_KALMAN_JUMP = 200.0

# Kalman filter configuration
PROCESS_NOISE = 0.03
MEASUREMENT_NOISE = 5.0


# ======================================================================
# REQUIRED COLUMNS
# ======================================================================

BALL_COLUMNS = [
    "frame",
    "time_sec",
    "center_x",
    "center_y",
    "confidence"
]


# ======================================================================
# LOAD DETECTION CSV
# ======================================================================

def load_detection_csv(
    detections_csv
):

    print(
        "\nLoading YOLO detection CSV..."
    )

    if not os.path.exists(
        detections_csv
    ):

        raise FileNotFoundError(
            f"Detection CSV not found:\n"
            f"{detections_csv}"
        )

    df = pd.read_csv(
        detections_csv
    )

    required_columns = [
        "frame",
        "time_sec",
        "class_id",
        "class_name",
        "confidence",
        "x1",
        "y1",
        "x2",
        "y2",
        "center_x",
        "center_y",
        "width",
        "height"
    ]

    missing_columns = [

        column

        for column in required_columns

        if column not in df.columns

    ]

    if missing_columns:

        raise ValueError(
            "Detection CSV is missing "
            f"columns:\n{missing_columns}"
        )

    print(
        f"Detection rows : {len(df):,}"
    )

    return df


# ======================================================================
# EXTRACT BALL POSITIONS
# ======================================================================

def extract_ball_positions(
    detections_df,
    output_dir
):

    print("\n" + "=" * 70)
    print("BALL POSITION EXTRACTION")
    print("=" * 70)

    # --------------------------------------------------------------
    # Find ball detections
    # --------------------------------------------------------------

    ball_df = detections_df[
        detections_df["class_name"]
        .astype(str)
        .str.lower()
        .eq("ball")
    ].copy()

    if ball_df.empty:

        raise RuntimeError(
            "No ball detections found in YOLO CSV."
        )

    # --------------------------------------------------------------
    # Sort by frame
    # --------------------------------------------------------------

    ball_df = (
        ball_df
        .sort_values(
            "frame"
        )
        .reset_index(
            drop=True
        )
    )

    # --------------------------------------------------------------
    # Multiple ball detections in one frame
    #
    # Keep the highest-confidence detection.
    # --------------------------------------------------------------

    ball_df = (
        ball_df
        .sort_values(
            [
                "frame",
                "confidence"
            ],
            ascending=[
                True,
                False
            ]
        )
        .drop_duplicates(
            subset=[
                "frame"
            ],
            keep="first"
        )
        .sort_values(
            "frame"
        )
        .reset_index(
            drop=True
        )
    )

    # --------------------------------------------------------------
    # Keep required columns
    # --------------------------------------------------------------

    ball_positions = ball_df[
        BALL_COLUMNS
    ].copy()

    # --------------------------------------------------------------
    # Add detection status
    # --------------------------------------------------------------

    ball_positions[
        "status"
    ] = "DETECTED"

    # --------------------------------------------------------------
    # Save
    # --------------------------------------------------------------

    output_csv = os.path.join(
        output_dir,
        "ball_positions.csv"
    )

    ball_positions.to_csv(
        output_csv,
        index=False
    )

    print(
        f"Ball detections : "
        f"{len(ball_positions):,}"
    )

    print(
        f"Output           : "
        f"{output_csv}"
    )

    return ball_positions


# ======================================================================
# CREATE ORIGINAL SAMPLED FRAME TIMELINE
# ======================================================================

def create_sampled_timeline(
    detections_df
):

    # --------------------------------------------------------------
    # The YOLO detector processes every 2nd frame.
    #
    # Every frame that appears in the detection CSV belongs to
    # the sampled YOLO timeline.
    #
    # We preserve ALL unique sampled frames here.
    # --------------------------------------------------------------

    sampled_frames = (

        detections_df[
            [
                "frame",
                "time_sec"
            ]
        ]

        .drop_duplicates(
            subset=[
                "frame"
            ]
        )

        .sort_values(
            "frame"
        )

        .reset_index(
            drop=True
        )
    )

    if sampled_frames.empty:

        raise RuntimeError(
            "Could not create sampled-frame timeline."
        )

    return sampled_frames


# ======================================================================
# BALL TRAJECTORY INTERPOLATION
# ======================================================================

def interpolate_ball_trajectory(
    ball_df,
    detections_df,
    output_dir
):

    print("\n" + "=" * 70)
    print("BALL TRAJECTORY INTERPOLATION")
    print("=" * 70)

    if ball_df.empty:

        raise RuntimeError(
            "No ball positions available."
        )

    # --------------------------------------------------------------
    # ORIGINAL YOLO SAMPLE TIMELINE
    # --------------------------------------------------------------

    sampled_frames = create_sampled_timeline(
        detections_df
    )

    # --------------------------------------------------------------
    # Keep only one ball position per frame
    # --------------------------------------------------------------

    ball_positions = (

        ball_df[
            [
                "frame",
                "center_x",
                "center_y",
                "confidence"
            ]
        ]

        .drop_duplicates(
            subset=[
                "frame"
            ]
        )

        .sort_values(
            "frame"
        )
    )

    # --------------------------------------------------------------
    # Merge ball positions onto ALL sampled frames
    # --------------------------------------------------------------

    trajectory = sampled_frames.merge(

        ball_positions,

        on="frame",

        how="left"

    )

    # --------------------------------------------------------------
    # Original YOLO detection mask
    # --------------------------------------------------------------

    detected_mask = (

        trajectory[
            "center_x"
        ].notna()

        &

        trajectory[
            "center_y"
        ].notna()

    )

    # --------------------------------------------------------------
    # Interpolate only inside actual detection regions.
    #
    # IMPORTANT:
    #
    # No new rows are created.
    #
    # We only fill missing positions inside the existing
    # sampled-frame timeline.
    # --------------------------------------------------------------

    trajectory[
        "center_x"
    ] = (

        trajectory[
            "center_x"
        ]

        .interpolate(
            method="linear",
            limit=MAX_INTERPOLATION_GAP,
            limit_area="inside"
        )
    )

    trajectory[
        "center_y"
    ] = (

        trajectory[
            "center_y"
        ]

        .interpolate(
            method="linear",
            limit=MAX_INTERPOLATION_GAP,
            limit_area="inside"
        )
    )

    # --------------------------------------------------------------
    # Status
    # --------------------------------------------------------------

    interpolated_mask = (

        ~detected_mask

        &

        trajectory[
            "center_x"
        ].notna()

        &

        trajectory[
            "center_y"
        ].notna()

    )

    lost_mask = (

        trajectory[
            "center_x"
        ].isna()

        |

        trajectory[
            "center_y"
        ].isna()

    )

    trajectory[
        "status"
    ] = "LOST"

    trajectory.loc[
        detected_mask,
        "status"
    ] = "DETECTED"

    trajectory.loc[
        interpolated_mask,
        "status"
    ] = "INTERPOLATED"

    # --------------------------------------------------------------
    # Save
    # --------------------------------------------------------------

    output_csv = os.path.join(

        output_dir,

        "ball_trajectory_interpolated.csv"

    )

    trajectory.to_csv(

        output_csv,

        index=False

    )

    detected_count = int(
        detected_mask.sum()
    )

    interpolated_count = int(
        interpolated_mask.sum()
    )

    lost_count = int(
        lost_mask.sum()
    )

    print(
        f"Original sampled frames : "
        f"{len(trajectory):,}"
    )

    print(
        f"Detected positions      : "
        f"{detected_count:,}"
    )

    print(
        f"Interpolated positions  : "
        f"{interpolated_count:,}"
    )

    print(
        f"Remaining missing       : "
        f"{lost_count:,}"
    )

    print(
        f"Output                  : "
        f"{output_csv}"
    )

    return trajectory


# ======================================================================
# CREATE KALMAN FILTER
# ======================================================================

def create_kalman_filter(
    initial_x,
    initial_y
):

    # State:
    #
    #   x
    #   y
    #   vx
    #   vy
    #
    kalman = cv2.KalmanFilter(
        4,
        2
    )

    # --------------------------------------------------------------
    # Transition matrix
    # --------------------------------------------------------------

    kalman.transitionMatrix = np.array(

        [
            [1, 0, 1, 0],
            [0, 1, 0, 1],
            [0, 0, 1, 0],
            [0, 0, 0, 1]
        ],

        dtype=np.float32
    )

    # --------------------------------------------------------------
    # Measurement matrix
    # --------------------------------------------------------------

    kalman.measurementMatrix = np.array(

        [
            [1, 0, 0, 0],
            [0, 1, 0, 0]
        ],

        dtype=np.float32
    )

    # --------------------------------------------------------------
    # Process noise
    # --------------------------------------------------------------

    kalman.processNoiseCov = (

        np.eye(
            4,
            dtype=np.float32
        )

        *

        PROCESS_NOISE

    )

    # --------------------------------------------------------------
    # Measurement noise
    # --------------------------------------------------------------

    kalman.measurementNoiseCov = (

        np.eye(
            2,
            dtype=np.float32
        )

        *

        MEASUREMENT_NOISE

    )

    # --------------------------------------------------------------
    # Initial state
    # --------------------------------------------------------------

    kalman.statePost = np.array(

        [
            [
                float(initial_x)
            ],

            [
                float(initial_y)
            ],

            [
                0.0
            ],

            [
                0.0
            ]

        ],

        dtype=np.float32
    )

    # --------------------------------------------------------------
    # Initial covariance
    # --------------------------------------------------------------

    kalman.errorCovPost = np.eye(

        4,

        dtype=np.float32

    )

    return kalman


# ======================================================================
# SAFE FLOAT EXTRACTION
# ======================================================================

def scalar_float(
    value
):

    array = np.asarray(
        value
    ).reshape(-1)

    if array.size == 0:

        return np.nan

    return float(
        array[0]
    )


# ======================================================================
# KALMAN BALL TRACKING
# ======================================================================

def apply_kalman_tracking(
    trajectory,
    output_dir
):

    print("\n" + "=" * 70)
    print("KALMAN BALL TRACKING")
    print("=" * 70)

    if trajectory.empty:

        raise RuntimeError(
            "Trajectory dataframe is empty."
        )

    # --------------------------------------------------------------
    # Ensure correct order
    # --------------------------------------------------------------

    trajectory = (

        trajectory

        .sort_values(
            "frame"
        )

        .reset_index(
            drop=True
        )

    )

    # --------------------------------------------------------------
    # Output rows
    # --------------------------------------------------------------

    output_rows = []

    # --------------------------------------------------------------
    # Kalman state
    # --------------------------------------------------------------

    kalman = None

    last_valid_x = None
    last_valid_y = None

    missing_count = 0

    # --------------------------------------------------------------
    # Process every sampled frame
    # --------------------------------------------------------------

    for _, row in trajectory.iterrows():

        frame = int(
            row["frame"]
        )

        time_sec = float(
            row["time_sec"]
        )

        status = str(
            row["status"]
        )

        measurement_x = row[
            "center_x"
        ]

        measurement_y = row[
            "center_y"
        ]

        has_measurement = (

            pd.notna(
                measurement_x
            )

            and

            pd.notna(
                measurement_y
            )

        )

        # ==========================================================
        # FIRST VALID DETECTION
        # ==========================================================

        if kalman is None:

            if not has_measurement:

                output_rows.append({

                    "frame":
                        frame,

                    "time_sec":
                        time_sec,

                    "center_x":
                        np.nan,

                    "center_y":
                        np.nan,

                    "velocity_x":
                        np.nan,

                    "velocity_y":
                        np.nan,

                    "confidence":
                        np.nan,

                    "source_status":
                        "LOST",

                    "status":
                        "LOST"

                })

                continue

            # ------------------------------------------------------
            # Initialize Kalman
            # ------------------------------------------------------

            initial_x = scalar_float(
                measurement_x
            )

            initial_y = scalar_float(
                measurement_y
            )

            kalman = create_kalman_filter(

                initial_x,

                initial_y

            )

            last_valid_x = initial_x
            last_valid_y = initial_y

            missing_count = 0

            output_rows.append({

                "frame":
                    frame,

                "time_sec":
                    time_sec,

                "center_x":
                    initial_x,

                "center_y":
                    initial_y,

                "velocity_x":
                    0.0,

                "velocity_y":
                    0.0,

                "confidence":
                    float(
                        row["confidence"]
                    )
                    if pd.notna(
                        row["confidence"]
                    )
                    else np.nan,

                "source_status":
                    status,

                "status":
                    "DETECTED"

            })

            continue

        # ==========================================================
        # KALMAN PREDICTION
        # ==========================================================

        prediction = kalman.predict()

        predicted_x = scalar_float(
            prediction[0]
        )

        predicted_y = scalar_float(
            prediction[1]
        )

        predicted_vx = scalar_float(
            prediction[2]
        )

        predicted_vy = scalar_float(
            prediction[3]
        )

        # ==========================================================
        # FRESH YOLO DETECTION
        # ==========================================================

        if status == "DETECTED" and has_measurement:

            measured_x = scalar_float(
                measurement_x
            )

            measured_y = scalar_float(
                measurement_y
            )

            # ------------------------------------------------------
            # Check jump from previous valid point
            # ------------------------------------------------------

            if (
                last_valid_x is not None
                and
                last_valid_y is not None
            ):

                jump = np.sqrt(

                    (
                        measured_x
                        -
                        last_valid_x
                    ) ** 2

                    +

                    (
                        measured_y
                        -
                        last_valid_y
                    ) ** 2

                )

            else:

                jump = 0.0

            # ------------------------------------------------------
            # Reject extreme detection jump
            # ------------------------------------------------------

            if jump > MAX_KALMAN_JUMP:

                # Treat this as a missing measurement
                missing_count += 1

                if (
                    missing_count
                    <= MAX_KALMAN_GAP
                ):

                    output_rows.append({

                        "frame":
                            frame,

                        "time_sec":
                            time_sec,

                        "center_x":
                            predicted_x,

                        "center_y":
                            predicted_y,

                        "velocity_x":
                            predicted_vx,

                        "velocity_y":
                            predicted_vy,

                        "confidence":
                            np.nan,

                        "source_status":
                            "REJECTED",

                        "status":
                            "KALMAN"

                    })

                else:

                    output_rows.append({

                        "frame":
                            frame,

                        "time_sec":
                            time_sec,

                        "center_x":
                            np.nan,

                        "center_y":
                            np.nan,

                        "velocity_x":
                            np.nan,

                        "velocity_y":
                            np.nan,

                        "confidence":
                            np.nan,

                        "source_status":
                            "REJECTED",

                        "status":
                            "LOST"

                    })

                continue

            # ------------------------------------------------------
            # Correct Kalman with measurement
            # ------------------------------------------------------

            measurement = np.array(

                [
                    [
                        measured_x
                    ],

                    [
                        measured_y
                    ]

                ],

                dtype=np.float32

            )

            corrected = kalman.correct(
                measurement
            )

            corrected_x = scalar_float(
                corrected[0]
            )

            corrected_y = scalar_float(
                corrected[1]
            )

            corrected_vx = scalar_float(
                corrected[2]
            )

            corrected_vy = scalar_float(
                corrected[3]
            )

            last_valid_x = corrected_x
            last_valid_y = corrected_y

            missing_count = 0

            output_rows.append({

                "frame":
                    frame,

                "time_sec":
                    time_sec,

                "center_x":
                    corrected_x,

                "center_y":
                    corrected_y,

                "velocity_x":
                    corrected_vx,

                "velocity_y":
                    corrected_vy,

                "confidence":
                    float(
                        row["confidence"]
                    )
                    if pd.notna(
                        row["confidence"]
                    )
                    else np.nan,

                "source_status":
                    "DETECTED",

                "status":
                    "DETECTED"

            })

            continue

        # ==========================================================
        # INTERPOLATED POSITION
        # ==========================================================

        if (
            status == "INTERPOLATED"
            and
            has_measurement
        ):

            measured_x = scalar_float(
                measurement_x
            )

            measured_y = scalar_float(
                measurement_y
            )

            # ------------------------------------------------------
            # Correct Kalman with interpolated position
            # ------------------------------------------------------

            measurement = np.array(

                [
                    [
                        measured_x
                    ],

                    [
                        measured_y
                    ]

                ],

                dtype=np.float32

            )

            corrected = kalman.correct(
                measurement
            )

            corrected_x = scalar_float(
                corrected[0]
            )

            corrected_y = scalar_float(
                corrected[1]
            )

            corrected_vx = scalar_float(
                corrected[2]
            )

            corrected_vy = scalar_float(
                corrected[3]
            )

            last_valid_x = corrected_x
            last_valid_y = corrected_y

            missing_count += 1

            if (
                missing_count
                <= MAX_KALMAN_GAP
            ):

                output_rows.append({

                    "frame":
                        frame,

                    "time_sec":
                        time_sec,

                    "center_x":
                        corrected_x,

                    "center_y":
                        corrected_y,

                    "velocity_x":
                        corrected_vx,

                    "velocity_y":
                        corrected_vy,

                    "confidence":
                        np.nan,

                    "source_status":
                        "INTERPOLATED",

                    "status":
                        "KALMAN"

                })

            else:

                output_rows.append({

                    "frame":
                        frame,

                    "time_sec":
                        time_sec,

                    "center_x":
                        np.nan,

                    "center_y":
                        np.nan,

                    "velocity_x":
                        np.nan,

                    "velocity_y":
                        np.nan,

                    "confidence":
                        np.nan,

                    "source_status":
                        "INTERPOLATED",

                    "status":
                        "LOST"

                })

            continue

        # ==========================================================
        # LOST FRAME
        # ==========================================================

        missing_count += 1

        if (
            missing_count
            <= MAX_KALMAN_GAP
        ):

            output_rows.append({

                "frame":
                    frame,

                "time_sec":
                    time_sec,

                "center_x":
                    predicted_x,

                "center_y":
                    predicted_y,

                "velocity_x":
                    predicted_vx,

                "velocity_y":
                    predicted_vy,

                "confidence":
                    np.nan,

                "source_status":
                    "LOST",

                "status":
                    "KALMAN"

            })

        else:

            output_rows.append({

                "frame":
                    frame,

                "time_sec":
                    time_sec,

                "center_x":
                    np.nan,

                "center_y":
                    np.nan,

                "velocity_x":
                    np.nan,

                "velocity_y":
                    np.nan,

                "confidence":
                    np.nan,

                "source_status":
                    "LOST",

                "status":
                    "LOST"

            })

    # --------------------------------------------------------------
    # Create dataframe
    # --------------------------------------------------------------

    kalman_df = pd.DataFrame(
        output_rows
    )

    # --------------------------------------------------------------
    # Save
    # --------------------------------------------------------------

    output_csv = os.path.join(

        output_dir,

        "ball_trajectory_kalman.csv"

    )

    kalman_df.to_csv(

        output_csv,

        index=False

    )

    # --------------------------------------------------------------
    # Statistics
    # --------------------------------------------------------------

    detected_count = int(

        (
            kalman_df[
                "status"
            ]

            ==

            "DETECTED"

        ).sum()

    )

    kalman_count = int(

        (
            kalman_df[
                "status"
            ]

            ==

            "KALMAN"

        ).sum()

    )

    lost_count = int(

        (
            kalman_df[
                "status"
            ]

            ==

            "LOST"

        ).sum()

    )

    valid_count = int(

        (

            kalman_df[
                "center_x"
            ].notna()

            &

            kalman_df[
                "center_y"
            ].notna()

        ).sum()

    )

    total_count = len(
        kalman_df
    )

    coverage = (

        valid_count
        /
        total_count
        *
        100

        if total_count > 0

        else 0

    )

    print(
        f"Kalman output rows : "
        f"{total_count:,}"
    )

    print(
        f"DETECTED           : "
        f"{detected_count:,}"
    )

    print(
        f"KALMAN             : "
        f"{kalman_count:,}"
    )

    print(
        f"LOST               : "
        f"{lost_count:,}"
    )

    print(
        f"Valid positions    : "
        f"{valid_count:,}"
    )

    print(
        f"Coverage           : "
        f"{coverage:.2f}%"
    )

    print(
        f"Output             : "
        f"{output_csv}"
    )

    return kalman_df


# ======================================================================
# CREATE FINAL BALL TRAJECTORY
# ======================================================================

def create_final_trajectory(
    kalman_df,
    output_dir
):

    print("\n" + "=" * 70)
    print("CREATING FINAL BALL TRAJECTORY")
    print("=" * 70)

    if kalman_df.empty:

        raise RuntimeError(
            "Kalman dataframe is empty."
        )

    final_df = (
        kalman_df
        .sort_values(
            "frame"
        )
        .reset_index(
            drop=True
        )
    )

    # --------------------------------------------------------------
    # Add convenience validity column
    # --------------------------------------------------------------

    final_df[
        "valid"
    ] = (

        final_df[
            "center_x"
        ].notna()

        &

        final_df[
            "center_y"
        ].notna()

    )

    # --------------------------------------------------------------
    # Calculate movement
    #
    # This will be useful for Stage 8C highlight scoring.
    # --------------------------------------------------------------

    final_df[
        "movement"
    ] = 0.0

    valid_indices = (
        final_df[
            "valid"
        ]
        .to_numpy()
    )

    x_values = (
        final_df[
            "center_x"
        ]
        .to_numpy(
            dtype=float
        )
    )

    y_values = (
        final_df[
            "center_y"
        ]
        .to_numpy(
            dtype=float
        )
    )

    for i in range(
        1,
        len(final_df)
    ):

        if (
            valid_indices[i]
            and
            valid_indices[i - 1]
        ):

            dx = (

                x_values[i]
                -
                x_values[i - 1]

            )

            dy = (

                y_values[i]
                -
                y_values[i - 1]

            )

            final_df.loc[
                i,
                "movement"
            ] = np.sqrt(

                dx ** 2
                +
                dy ** 2

            )

    # --------------------------------------------------------------
    # Save
    # --------------------------------------------------------------

    output_csv = os.path.join(

        output_dir,

        "ball_trajectory_final.csv"

    )

    final_df.to_csv(

        output_csv,

        index=False

    )

    print(
        f"Final trajectory rows : "
        f"{len(final_df):,}"
    )

    print(
        f"Output                : "
        f"{output_csv}"
    )

    return final_df


# ======================================================================
# MAIN BALL TRACKING PIPELINE
# ======================================================================

def track_ball(
    detections_csv,
    output_dir
):

    print("=" * 70)
    print("BALL TRACKING PIPELINE")
    print("=" * 70)

    # --------------------------------------------------------------
    # Create output directory
    # --------------------------------------------------------------

    os.makedirs(

        output_dir,

        exist_ok=True

    )

    # --------------------------------------------------------------
    # Load detections
    # --------------------------------------------------------------

    detections_df = load_detection_csv(

        detections_csv

    )

    # --------------------------------------------------------------
    # Extract ball detections
    # --------------------------------------------------------------

    ball_df = extract_ball_positions(

        detections_df,

        output_dir

    )

    # --------------------------------------------------------------
    # Interpolation
    # --------------------------------------------------------------

    interpolated_df = (

        interpolate_ball_trajectory(

            ball_df,

            detections_df,

            output_dir

        )

    )

    # --------------------------------------------------------------
    # Kalman tracking
    # --------------------------------------------------------------

    kalman_df = apply_kalman_tracking(

        interpolated_df,

        output_dir

    )

    # --------------------------------------------------------------
    # Final trajectory
    # --------------------------------------------------------------

    final_df = create_final_trajectory(

        kalman_df,

        output_dir

    )

    # --------------------------------------------------------------
    # Statistics
    # --------------------------------------------------------------

    detected_count = int(

        (
            final_df[
                "status"
            ]

            ==

            "DETECTED"

        ).sum()

    )

    kalman_count = int(

        (
            final_df[
                "status"
            ]

            ==

            "KALMAN"

        ).sum()

    )

    lost_count = int(

        (
            final_df[
                "status"
            ]

            ==

            "LOST"

        ).sum()

    )

    valid_count = int(

        final_df[
            "valid"
        ].sum()

    )

    trajectory_rows = len(
        final_df
    )

    coverage = (

        valid_count
        /
        trajectory_rows
        *
        100

        if trajectory_rows > 0

        else 0

    )

    # --------------------------------------------------------------
    # Paths
    # --------------------------------------------------------------

    ball_positions_csv = os.path.join(

        output_dir,

        "ball_positions.csv"

    )

    interpolated_csv = os.path.join(

        output_dir,

        "ball_trajectory_interpolated.csv"

    )

    kalman_csv = os.path.join(

        output_dir,

        "ball_trajectory_kalman.csv"

    )

    final_csv = os.path.join(

        output_dir,

        "ball_trajectory_final.csv"

    )

    # --------------------------------------------------------------
    # Final output
    # --------------------------------------------------------------

    print("\n" + "=" * 70)
    print("BALL TRACKING COMPLETE")
    print("=" * 70)

    print(
        f"\nYOLO ball detections : "
        f"{len(ball_df):,}"
    )

    print(
        f"Trajectory rows      : "
        f"{trajectory_rows:,}"
    )

    print(
        f"DETECTED             : "
        f"{detected_count:,}"
    )

    print(
        f"KALMAN               : "
        f"{kalman_count:,}"
    )

    print(
        f"LOST                 : "
        f"{lost_count:,}"
    )

    print(
        f"Valid positions      : "
        f"{valid_count:,}"
    )

    print(
        f"Effective coverage   : "
        f"{coverage:.2f}%"
    )

    print(
        "\nOUTPUT DIRECTORY:"
    )

    print(
        output_dir
    )

    print(
        "\nFiles:"
    )

    print(
        ball_positions_csv
    )

    print(
        interpolated_csv
    )

    print(
        kalman_csv
    )

    print(
        final_csv
    )

    print(
        "=" * 70
    )

    return {

        "detections_csv":
            detections_csv,

        "output_dir":
            output_dir,

        "ball_detections":
            len(ball_df),

        "trajectory_rows":
            trajectory_rows,

        "detected":
            detected_count,

        "kalman":
            kalman_count,

        "lost":
            lost_count,

        "valid_positions":
            valid_count,

        "coverage":
            coverage,

        "ball_positions_csv":
            ball_positions_csv,

        "interpolated_csv":
            interpolated_csv,

        "kalman_csv":
            kalman_csv,

        "final_csv":
            final_csv

    }


# ======================================================================
# DIRECT EXECUTION
# ======================================================================

if __name__ == "__main__":

    print(
        "\nThis file is a reusable backend pipeline."
    )

    print(
        "Call track_ball() from the FastAPI backend."
    )